[directory]
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_status]
disabled = true

[character]
success_symbol = "[→](bold green)"
error_symbol = "[←](bold red)"

[username]
format = "[$user]($style) "
show_always = true
disabled = false

[memory_usage]
threshold = -1
format = "[$symbol$ram_pct]($style)"
symbol = "RAM: "
disabled = false