[directory]
truncation_length = 4
truncate_to_repo = false

[git_status]
disabled = true

[character]
success_symbol = "[→](bold green)"
error_symbol = "[←](bold red)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false